// <auto-generated />
using System;
using Freem.Entities.Storage.PostgreSQL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freem.Entities.Storage.PostgreSQL.Migrations.Instances
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240826032629_AddAuditableEntityAgain")]
    partial class AddAuditableEntityAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_entities")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core_entities", "category_status", new[] { "active", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core_entities", "event_action", new[] { "created", "updated", "removed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("core_entities.category_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("categories_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("categories_user_id_idx");

                    b.ToTable("categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.Base.BaseEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<int>("Action")
                        .HasColumnType("event_action")
                        .HasColumnName("action")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("events_pk");

                    b.ToTable("events", "core_entities");

                    b.HasDiscriminator<string>("EventType").IsComplete(true).HasValue("BaseEventEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("records_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("records_user_id_idx");

                    b.ToTable("records", "core_entities", t =>
                        {
                            t.HasCheckConstraint("records_users_check", "start_at <= end_at");
                        });
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.CategoryTagRelationEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("CategoryId", "TagId")
                        .HasName("categories_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("categories_tags_tag_id_idx");

                    b.ToTable("categories_tags", "core_entities", t =>
                        {
                            t.HasTrigger("check_categories_tags_user_ids_trigger");
                        });
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordCategoryRelationEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.HasKey("RecordId", "CategoryId")
                        .HasName("records_categories_pk");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("records_categories_category_id_idx");

                    b.ToTable("records_categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordTagRelationEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("RecordId", "TagId")
                        .HasName("records_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("records_tags_tag_id_idx");

                    b.ToTable("records_tags", "core_entities", t =>
                        {
                            t.HasTrigger("check_records_tags_user_ids_trigger");
                        });
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordCategoryRelationEntity", b =>
                {
                    b.Property<string>("RunningRecordUserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.HasKey("RunningRecordUserId", "CategoryId")
                        .HasName("running_records_categories_pk");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("running_records_categories_category_id_idx");

                    b.ToTable("running_records_categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordTagRelationEntity", b =>
                {
                    b.Property<string>("RunningRecordUserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("RunningRecordUserId", "TagId")
                        .HasName("running_records_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("running_records_tags_tag_id_idx");

                    b.ToTable("running_records_tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("running_records_pk");

                    b.ToTable("running_records", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tags_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("tags_user_id_unique");

                    b.HasIndex("Name", "UserId")
                        .IsUnique()
                        .HasDatabaseName("tags_name_unique");

                    b.ToTable("tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.ToTable("users", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.CategoryEventEntity", b =>
                {
                    b.HasBaseType("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.Base.BaseEventEntity");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.HasDiscriminator().HasValue("category");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.RecordEventEntity", b =>
                {
                    b.HasBaseType("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.Base.BaseEventEntity");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.HasDiscriminator().HasValue("record");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.RunningRecordEventEntity", b =>
                {
                    b.HasBaseType("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.Base.BaseEventEntity");

                    b.HasDiscriminator().HasValue("running_record");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.TagEventEntity", b =>
                {
                    b.HasBaseType("Freem.Entities.Storage.PostgreSQL.Database.Entities.Events.Base.BaseEventEntity");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasDiscriminator().HasValue("tags");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.CategoryTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_tags_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_tags_tags_fk");

                    b.Navigation("Category");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordCategoryRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_categories_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_categories_records_fk");

                    b.Navigation("Category");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_tags_records_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_tags_tags_fk");

                    b.Navigation("Record");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordCategoryRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_categories_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", "RunningRecord")
                        .WithMany()
                        .HasForeignKey("RunningRecordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_categories_running_records_fk");

                    b.Navigation("Category");

                    b.Navigation("RunningRecord");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", "RunningRecord")
                        .WithMany()
                        .HasForeignKey("RunningRecordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_tags_running_records_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_tags_tags_fk");

                    b.Navigation("RunningRecord");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tags_users_fk");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
