// <auto-generated />
using System;
using Freem.Entities.Storage.PostgreSQL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freem.Entities.Storage.PostgreSQL.Migrations.Instances
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240513035000_MvpModelsMigration")]
    partial class MvpModelsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_entities")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core_entities", "category_status", new[] { "active", "archived" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("core_entities.category_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("categories_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("categories_user_id_idx");

                    b.ToTable("categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("records_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("records_user_id_idx");

                    b.ToTable("records", "core_entities", t =>
                        {
                            t.HasCheckConstraint("records_users_check", "start_at <= end_at");
                        });
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.CategoryTagRelationEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("CategoryId", "TagId")
                        .HasName("categories_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("categories_tags_tag_id_idx");

                    b.ToTable("categories_tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordCategoryRelationEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.HasKey("RecordId", "CategoryId")
                        .HasName("records_categories_pk");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("records_categories_category_id_idx");

                    b.ToTable("records_categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordTagRelationEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("RecordId", "TagId")
                        .HasName("records_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("records_tags_tag_id_idx");

                    b.ToTable("records_tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordCategoryRelationEntity", b =>
                {
                    b.Property<string>("RunningRecordId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.HasKey("RunningRecordId", "CategoryId")
                        .HasName("running_records_categories_pk");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("running_records_categories_category_id_idx");

                    b.ToTable("running_records_categories", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordTagRelationEntity", b =>
                {
                    b.Property<string>("RunningRecordId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("RunningRecordId", "TagId")
                        .HasName("running_records_tags_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("running_records_tags_tag_id_idx");

                    b.ToTable("running_records_tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("running_records_pk");

                    b.ToTable("running_records", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tags_pk");

                    b.HasIndex("UserId")
                        .HasDatabaseName("tags_user_id_unique");

                    b.HasIndex("Name", "UserId")
                        .IsUnique()
                        .HasDatabaseName("tags_name_unique");

                    b.ToTable("tags", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.ToTable("users", "core_entities");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.CategoryTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_tags_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_tags_tags_fk");

                    b.Navigation("Category");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordCategoryRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_categories_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_categories_records_fk");

                    b.Navigation("Category");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RecordTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_tags_records_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_tags_tags_fk");

                    b.Navigation("Record");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordCategoryRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_categories_categories_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", "RunningRecord")
                        .WithMany()
                        .HasForeignKey("RunningRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_categories_running_records_fk");

                    b.Navigation("Category");

                    b.Navigation("RunningRecord");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.Relations.RunningRecordTagRelationEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", "RunningRecord")
                        .WithMany()
                        .HasForeignKey("RunningRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_tags_running_records_fk");

                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_tags_tags_fk");

                    b.Navigation("RunningRecord");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.RunningRecordEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("running_records_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freem.Entities.Storage.PostgreSQL.Database.Entities.TagEntity", b =>
                {
                    b.HasOne("Freem.Entities.Storage.PostgreSQL.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tags_users_fk");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
